app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/nottte
    username: ${env.POSTGRES_USERNAME}
    password: ${env.POSTGRES_PASSWORD}
    pool-size: 30
spring:
  flyway:
    baseline-on-migrate: true
