# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      with:
        java-version: 1.11
    - uses: harmon758/postgresql-action@v1
    - name: Make PostgreSQL server
      with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
      uses: actions/setup-java@v1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
